name: UVASOMIT/action-release-with-assets
description: |
  GitHub Release Action with Assets
author: UVASOMIT
branding:
  icon: box
  color: gray-dark
inputs:
  commitish:
    description: Commit branch
    required: true
    default: master
  token:
    description: The GitHub token.
    required: true
    default: ''
  tag:
    description: An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
    default: ''
  name:
    required: true
  prerelease:
    default: false
  files:
    required: false
    default: ''
  body:
    default: ''
runs:
  using: node10
  main: action.js
